### ISSUE TITLE
There is no config for this plugin (caused NullPointerException)

### ISSUE THREAD

**Issue by SpraxDev** [ShakerLP/MCWebi#1]
It's empty inside here... I hope you'll read this :D - So here is the error

Please send this error to developer ShakerLP
And please restart/reload you plugins!Back

Version: 1.30b
MC-Version: git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
Plugins: PermissionsEx, MCWebi, EmptyWorldGenerator, BlockLaby, ServerUtils, PacketListenerApi, ProtocolLib, NoCheatPlus, NickNamer, LobbyHandler,
Time: 1469459464023
Parms: {path=./plugins/PacketListenerApi, action=filebrowser}
Error:
java.lang.NullPointerException
at me.ShakerLP.Actions.Actions.Action(Actions.java:1010)
at me.ShakerLP.Functions.DebugServer.serve(DebugServer.java:235)
at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:923)
at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
at java.lang.Thread.run(Thread.java:745)

**Comment by ShakerLP** [comment]
Soory for this late answer.
I fix All Old Bugs in the recode :)

**Comment by SpraxDev** [comment]
Ok nice :) - Thanks for the nice and free Plugin <3

**Comment by ShakerLP** [comment]
Here you can see a little image from the new MCWebi.
https://eriks-screenshots.de/6sjy.png

PS: I will add an API and more :)
